git fetch AlexandrovichValeria # Александрович 
git fetch Olexsa               # Арсеньтьева   
git fetch youngwow             # Бояркин       
git fetch PrivalovAI           # Девятериков   
git fetch Packword             # Желнин        
git fetch Zhivaev              # Живаев        
git fetch WoodMan777           # Зенин         
git fetch MindlessDoc          # Козлов        
git fetch korotkovandrew       # Коротков      
git fetch AlexKulikovMOEVM     # Куликов       
git fetch karinotc             # Куртова       
git fetch alex2210-alt         # Кусмарцев     
git fetch Vladis4791           # Парфенов      
git fetch Mixagit              # Пенкин        
git fetch rednamgo             # Петровская    
git fetch PodoprigoraIvan      # Подопригора   
git fetch jordon43             # Позолотин     
git fetch Luthineth            # Пустовалова   
git fetch iulia-rudakova       # Рудакова      
git fetch C00LNICK             # Сабанов       
git fetch Troloroma            # Самара        
git fetch SergevninDmitry      # Сергевнин     
git fetch HippoMaru            # Смирнов       
git fetch ForthA               # Тарасов       
git fetch MaLysHer             # Трофимов      
git fetch xaninam              # Ханина        
