git remote add  AlexandrovichValeria https://github.com/AlexandrovichValeria/spbetu_comparch_2021_0383.git # Александрович 
git remote add  Olexsa               https://github.com/Olexsa/spbetu_comparch_2021_0383.git                # Арсеньтьева   
git remote add  youngwow             https://github.com/youngwow/spbetu_comparch_2021_0383.git              # Бояркин       
git remote add  PrivalovAI           https://github.com/PrivalovAI/spbetu_comparch_2021_0383.git            # Девятериков   
git remote add  Packword             https://github.com/Packword/spbetu_comparch_2021_0383.git              # Желнин        
git remote add  Zhivaev              https://github.com/Zhivaev/spbetu_comparch_2021_0383.git               # Живаев        
git remote add  WoodMan777           https://github.com/WoodMan777/spbetu_comparch_2021_0383.git            # Зенин         
git remote add  MindlessDoc          https://github.com/MindlessDoc/spbetu_comparch_2021_0383.git           # Козлов        
git remote add  korotkovandrew       https://github.com/korotkovandrew/spbetu_comparch_2021_0383.git        # Коротков      
git remote add  AlexKulikovMOEVM     https://github.com/AlexKulikovMOEVM/spbetu_comparch_2021_0383.git      # Куликов       
git remote add  karinotc             https://github.com/karinotc/spbetu_comparch_2021_0383.git              # Куртова       
git remote add  alex2210-alt         https://github.com/alex2210-alt/spbetu_comparch_2021_0383.git          # Кусмарцев     
git remote add  Vladis4791           https://github.com/Vladis4791/spbetu_comparch_2021_0383.git            # Парфенов      
git remote add  Mixagit              https://github.com/Mixagit/spbetu_comparch_2021_0383.git               # Пенкин        
git remote add  rednamgo             https://github.com/rednamgo/spbetu_comparch_2021_0383.git              # Петровская    
git remote add  PodoprigoraIvan      https://github.com/PodoprigoraIvan/spbetu_comparch_2021_0383.git       # Подопригора   
git remote add  jordon43             https://github.com/jordon43/spbetu_comparch_2021_0383.git              # Позолотин     
git remote add  Luthineth            https://github.com/Luthineth/spbetu_comparch_2021_0383.git             # Пустовалова   
git remote add  iulia-rudakova       https://github.com/iulia-rudakova/spbetu_comparch_2021_0383.git        # Рудакова      
git remote add  C00LNICK             https://github.com/C00LNICK/spbetu_comparch_2021_0383.git              # Сабанов       
git remote add  Troloroma            https://github.com/Troloroma/spbetu_comparch_2021_0383.git             # Самара        
git remote add  SergevninDmitry      https://github.com/SergevninDmitry/spbetu_comparch_2021_0383.git       # Сергевнин     
git remote add  HippoMaru            https://github.com/HippoMaru/spbetu_comparch_2021_0383.git             # Смирнов       
git remote add  ForthA               https://github.com/ForthA/spbetu_comparch_2021_0383.git                # Тарасов       
git remote add  MaLysHer             https://github.com/MaLysHer/spbetu_comparch_2021_0383.git              # Трофимов      
git remote add  xaninam              https://github.com/xaninam/spbetu_comparch_2021_0383.git               # Ханина        
